server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的RabbitMQ的服务信息
        defaultRabbit: #表示定义的名称，用于binding结合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq相关配置环境
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的exchange定义
          content-type: application/json #文本是text/plain
          binder: defaultRabbit #设置要绑定消息服务的具体位置
          group: yshaA

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔， 默认30
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔，默认90
    instance-id: receive-8803.com
    prefer-ip-address: true

