server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: LasVegas@312

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ys.entities
