server:
  port: 83
spring:
  application:
    name: cloud-order-service-alibaba
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://cloud-payment-service-alibaba
